config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/test_sign_in' => 'users/sessions#test_sign_in'
  end
  resource :users, only: [:show]
  get 'mypage/diary' => 'users#mypage_diary', as: 'mypage_diary'
  get 'mypage/post' => 'users#mypage_post', as: 'mypage_post'
  get 'mypage/like' => 'users#mypage_like', as: 'mypage_like'
  get 'chart/study' => 'users#chart_study', as: 'chart_study'
  get 'chart/sleeping' => 'users#chart_sleeping', as: 'chart_sleeping'
  get 'chart/exercise' => 'users#chart_exercise', as: 'chart_exercise'
  get 'customs/management' => 'customs#management'
  resources :customs, only: [:index, :create, :destroy]
  post 'task_complete/:id' => 'custom_records#create', as: 'task_complete'
  resources :posts, only: [:new, :index, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  get 'search/post' => 'posts#post_search', as: 'post_search'
  resources :genres, only: [:index, :create, :destroy]
  resources :diaries
  resources :lives, only: [:update]
  resources :life_recodes, only: [:index, :edit, :update]
  resources :inquiries, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customs, dependent: :destroy
  has_many :custom_records, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :genres, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :life_recodes, dependent: :destroy
  #refileの設定
  attachment :profile_image

  validates :name, presence: true, length:{in: 2..10 }
  validates :acount_name, presence: true, format: { with: /@+\w{6,12}/}, uniqueness: true
  validates :introduction, presence: true, length:{maximum: 100}


  def self.test_sign_in
    User.find_by(email: "test_user@example.com")
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :check_test_user, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  #新規登録後のパス
  def after_sign_up_path_for(resource)
    customs_path
  end

  #登録情報編集後のパス
  def after_update_path_for(resource)
    users_path
  end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :acount_name, :introduction, :profile_image, :password])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :acount_name, :introduction, :profile_image])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def check_test_user
    if resource.email == "test_user@example.com"
      redirect_to edit_user_registration_path
      flash[:notice] = "サンプルユーザーは変更できません。"
    end
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  #ログイン後のパス
  def after_sign_in_path_for(resource)
    customs_path
  end
  #ログアウト後のパス
  def after_sign_out_path_for(resource)
    root_path
  end

  def test_sign_in
    user = User.test_sign_in
    sign_in user
    redirect_to customs_path, notice: "サンプルユーザーとしてログインしました。"
  end

   #protected


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = current_user
		@diaries = current_user.diaries
		@posts = current_user.posts
		@like_posts = @user.posts
		@life_recodes = current_user.life_recodes
	end

	def mypage_diary
		@user = current_user
		@diaries = current_user.diaries
	end

	def mypage_post
		@user = current_user
		@posts = current_user.posts
	end

	def mypage_like
		@user = current_user
		@like_posts = @user.like_posts
	end

	def chart_study
		@life_recodes = current_user.life_recodes
	end

	def chart_sleeping
		@life_recodes = current_user.life_recodes
	end

	def chart_exercise
		@life_recodes = current_user.life_recodes
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/chart_exercise.js.erb
$('#chart').html("<%= j(render 'shared/chart_exercise', { life_recodes: @life_recodes }) %>");

app/views/users/chart_sleeping.js.erb
$('#chart').html("<%= j(render 'shared/chart_sleeping', { life_recodes: @life_recodes }) %>");

app/views/users/chart_study.js.erb
$('#chart').html("<%= j(render 'shared/chart_study', { life_recodes: @life_recodes }) %>");

app/views/users/mypage_diary.js.erb
$('#mypage-tab').html("<%= j(render 'shared/mypage_diary', { diaries: @diaries }) %>");

app/views/users/mypage_like.js.erb
$('#mypage-tab').html("<%= j(render 'shared/mypage_like', { like_posts: @like_posts }) %>");

app/views/users/mypage_post.js.erb
$('#mypage-tab').html("<%= j(render 'shared/mypage_post', { posts: @posts }) %>");

app/views/users/show.html.erb
<div class="container">
	<div class="page-title text-center b-primary mt-5">
		<h1>マイページ</h1>
	</div>
	<div class="row mt-3 pb-5 mypage-border">
		<div class="col-md-3 border text-center mypage py-2">
			<%= image_tag attachment_url(@user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no-img.png"), size: "100x100", class:"profile-image" %>
			<p class="">
				<%= @user.name %><br>
				<%= @user.acount_name %><br>
				日記：<%= @user.diaries.count %><br>
				投稿：<%= @user.posts.count %><br>
				<%= @user.introduction %>
			</P>
			<%= link_to "会員登録情報編集", edit_user_registration_path(@user), class:"btn btn-success", 'data-turbolinks':false %>
			<%= link_to "生活を見る", life_recodes_path, class:"btn btn-primary mt-2", 'data-turbolinks':false %>
		</div>
		<div class="col-md-9 bg-chart border">
			<%= link_to "学習時間", chart_study_path, remote: true, class:"btn btn-primary" %>
			<%= link_to "睡眠時間", chart_sleeping_path, remote: true, class:"btn btn-info" %>
			<%= link_to "運動時間", chart_exercise_path, remote: true, class:"btn btn-success" %>
			<div id="chart">
				<%= render 'shared/chart_study', { life_recodes: @life_recodes } %>
			</div>
		</div>
	</div>
	<div class="row mt-5">
		<div class="col-md-12">
			<ul class="nav nav-tabs">
				<li class="nav-item"><%= link_to "日記", mypage_diary_path, remote: true, class:"nav-link px-5 border tab-bg" %></li>
				<li class="nav-item"><%= link_to "投稿", mypage_post_path, remote: true, class:"nav-link px-5 border tab-bg" %></li>
				<li class="nav-item"><%= link_to "いいね", mypage_like_path, remote: true, class:"nav-link px-5 border tab-bg" %></li>
			</ul>
			<div id="mypage-tab" class="mypage-tabbox">
				<%= render 'shared/mypage_diary', { diaries: @diaries } %>
			</div>
		</div>
	</div>
</div>