config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/test_sign_in' => 'users/sessions#test_sign_in'
  end
  resource :users, only: [:show]
  get 'mypage/diary' => 'users#mypage_diary', as: 'mypage_diary'
  get 'mypage/post' => 'users#mypage_post', as: 'mypage_post'
  get 'mypage/like' => 'users#mypage_like', as: 'mypage_like'
  get 'chart/study' => 'users#chart_study', as: 'chart_study'
  get 'chart/sleeping' => 'users#chart_sleeping', as: 'chart_sleeping'
  get 'chart/exercise' => 'users#chart_exercise', as: 'chart_exercise'
  get 'customs/management' => 'customs#management'
  resources :customs, only: [:index, :create, :destroy]
  post 'task_complete/:id' => 'custom_records#create', as: 'task_complete'
  resources :posts, only: [:new, :index, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  get 'search/post' => 'posts#post_search', as: 'post_search'
  resources :genres, only: [:index, :create, :destroy]
  resources :diaries
  resources :lives, only: [:update]
  resources :life_recodes, only: [:index, :edit, :update]
  resources :inquiries, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/custom.rb
class Custom < ApplicationRecord
	belongs_to :user
	has_many :custom_records, dependent: :destroy

	validates :user_id, presence: true
	validates :task, presence: true, length:{maximum:20}
	validates :task_status, presence: true

	enum	task_status: [:未達成, :達成]

	def self.task_complete
		unless self.count == 0
			@task = self.pluck(:task_status)
			@task.all?{|task| task == "達成"}
		end
	end
end

app/models/custom_record.rb
class CustomRecord < ApplicationRecord
	belongs_to :custom
	belongs_to :user

	validates :user_id, presence: true
	validates :custom_id, presence: true
	validates :start_time, presence: true

end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :user
	belongs_to :genre

	validates :user_id, presence: true
	validates :genre_id, presence: true
	validates :title, presence: true, length:{maximum:50}
	validates :body, presence: true, length:{maximum:500}
	validates :diary_date, presence: true
	validates :adequacy, presence: true


end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :user
  has_many :diaries, dependent: :destroy

  validates :user_id, presence: true
  validates :name, presence: true, length:{maximum:15}
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/life.rb
class Life < ApplicationRecord
	belongs_to :user

	validates :user_id, presence: true
	validates :study_time, presence: true
	validates :sleeping_time, presence: true
	validates :exercise_time, presence: true
	validates :study_memo, length:{maximum:50}
	validates :sleeping_memo, length:{maximum:50}
	validates :exercise_memo, length:{maximum:50}
end

app/models/life_recode.rb
class LifeRecode < ApplicationRecord
	belongs_to :user

	validates :user_id, presence: true
	validates :study_time, presence: true
	validates :sleeping_time, presence: true
	validates :exercise_time, presence: true
	validates :study_memo, length:{maximum:100}
	validates :sleeping_memo, length:{maximum:100}
	validates :exercise_memo, length:{maximum:100}
	validates :life_date, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	#refileの設定
	attachment :post_image

	validates :user_id, presence: true
	validates :content, presence: true, length:{maximum:30}
	validates :post_image, presence: true

	def liked_by?(user)
  		likes.where(user_id: user.id).exists?
	end

	def save_tag(sent_tags)
		current_tags = self.tags.pluck(:name) unless self.tags.nil?
		old_tags = current_tags - sent_tags
		new_tags = sent_tags - current_tags

		old_tags.each do |old|
			self.tags.delete Tag.find_by(name: old)
		end

		new_tags.each do |new|
			new_post_tag = Tag.find_or_create_by(name: new)
			self.tags << new_post_tag
		end
	end

	def self.search(search)
		if search
			Post.where(['content LIKE ?', "%#{search}%"])
		else
			Post.all
		end
	end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, length:{maximum:15}


  #検索機能
  def self.search(search)
  	Tag.where(['name LIKE ?', "%#{search}%"])
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customs, dependent: :destroy
  has_many :custom_records, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :genres, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :life_recodes, dependent: :destroy
  #refileの設定
  attachment :profile_image

  validates :name, presence: true, length:{in: 2..10 }
  validates :acount_name, presence: true, format: { with: /@+\w{6,12}/}, uniqueness: true
  validates :introduction, presence: true, length:{maximum: 100}


  def self.test_sign_in
    User.find_by(email: "test_user@example.com")
  end

end

app/controllers/customs_controller.rb
class CustomsController < ApplicationController
	before_action :authenticate_user!


	def index
		@customs = current_user.customs
		@custom_records = current_user.custom_records
		@life = Life.find_or_create_by(user_id: current_user.id)
	end

	def management
		@custom = Custom.new
		@customs = current_user.customs
		@custom_records = current_user.custom_records
	end

	def create
		@custom = Custom.new(custom_params)
		@custom.user = current_user
		if @custom.save
			flash[:success] = "新しい習慣を追加しました！今日から続けよう！"
			redirect_to customs_path
		else
			@customs = Custom.where(user_id: current_user)
			render 'management'
		end
	end

	def destroy
		@custom = Custom.find(params[:id])
		if @custom.destroy
			flash[:danger] = "習慣を削除しました"
			redirect_to customs_management_path
		else
			render 'management'
		end
	end




	private
		def custom_params
			params.require(:custom).permit(:task)
		end


end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper


	def adequacy_status(diary)
		case diary.adequacy
			when 1
				image_tag asset_path('nicochan5.png'), class:"diary-image-mypage"
			when 2
				image_tag asset_path('nicochan4.png'), class:"diary-image-mypage"
			when 3
				image_tag asset_path('nicochan1.png'), class:"diary-image-mypage"
			when 4
				image_tag asset_path('nicochan2.png'), class:"diary-image-mypage"
			when 5
				image_tag asset_path('nicochan3.png'), class:"diary-image-mypage"
		end
	end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lives_helper.rb
module LivesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customs/index.html.erb
<div class="container">
	<div class="row justify-content-center custom-index-top">
		<div class="col-md-4">
			<%= image_tag 'mylife-logo5.png', class:"img-fluid", id:"home-image" %>
		</div>
	</div>
	<div class="row mt-1 justify-content-center">
		<div class="col-8">
			<div class="row justify-content-between">
			<%= link_to customs_management_path, class:"col-3" do %>
				<div class="box-custom mx-auto text-center">
					<%= image_tag asset_path('custom-logo.png'), class:"img-width img-fluid" %>
				</div>
			<% end %>
			<%= link_to diaries_path, class:"col-3" do %>
				<div class="box-diary mx-auto text-center">
					<%= image_tag asset_path('diary-logo.png'), class:"img-width img-fluid" %>
				</div>
			<% end %>
			<%= link_to posts_path, class:"col-3" do %>
				<div class="box-post mx-auto text-center">
					<%= image_tag asset_path('post-logo.png'), class:"img-width img-fluid" %>
				</div>
			<% end %>
			</div>
		</div>
	</div>
	<div class="row py-3 justify-content-center">
		<div class=" col-md-5 bg-white">
			<%= month_calendar events: @custom_records do |date, custom_records| %>
				<%= date.strftime("%d日") %><br>
				<% custom_records.each do |custom_record| %>
				<span class="" data-trigger="click" data-placement="top" title="<%= custom_record.custom.task %>">
					<i class="fas fa-chevron-circle-down"></i>
				</span>
				<% end %>
			<% end %>
		</div>
		<div class="col-md-5">
			<h3 class="text-center task-title bg-blue2">毎日のタスク  全<%= @customs.count %>件
				<span class="h5" data-toggle="popover" data-placement="top" data-content="毎日00:00にリセットされます">
					<i class="far fa-question-circle"></i>
				</span>
			</h3>
			<div class="custom-table px-5 mt-4 mb-2 task-index">
				<table class="table">
					<% if @customs.count == 0 %>
						<div class="text-center mt-3">
							<h4>タスクを設定しよう！</h4>
						</div>
					<% elsif @customs.task_complete %>
						<div class="task-complete">
							<%= image_tag 'complete.png', class:"img-fluid", id:"complete-image" %>
						</div>
					<% end %>
					<tbody>
						<% @customs.each do |custom| %>
						<tr>
							<td class="w-50">
								<%= custom.task %>
							</td>
							<td class="w-25 text-center">
								<% if custom.task_status == "未達成" %>
									<span class="badge badge-info"><%= custom.task_status %></span>
								<% else %>
									<span class="badge badge-warning"><%= custom.task_status %></span>
								<% end %>
							</td>
							<td class="w-25 text-center">
								<% if custom.task_status == "未達成" %>
								<%= link_to "達成", task_complete_path(custom.id), id:"task_button", method: :post %>
								<% end %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<div class="row">
				<div class="col-md-12 mt-3">
					<h3 class="text-center task-title bg-blue2">
						生活記録
						<span class="h5" data-toggle="popover" data-placement="top" data-content="毎日23:59に記録されます">
							<i class="far fa-question-circle"></i>
						</span>
					</h3>
					<div class="life-form">
						<%= form_with model: @life, class:"form-inline" do |f| %>
							 	<div class="form-group form-row">
									<%= f.label :study_time, "勉強時間", class:"col-6 col-form-label text-md-right" %>
									<%= f.text_field :study_time, class:"form-control col-4" %>分
									<%= render 'shared/modal_study', { f: f } %>
								</div>
								<div class="form-group form-row">
									<%= f.label :sleeping_time, "睡眠時間", class:"col-6 col-form-label text-md-right" %>
									<%= f.text_field :sleeping_time, class:"form-control col-4" %>分
									<%= render 'shared/modal_sleeping', { f: f } %>
								</div>
								<div class="form-group form-row">
									<%= f.label :exercise_time, "運動時間", class:"col-6" %>
									<%= f.text_field :exercise_time, class:"form-control col-4" %>分
									<%= render 'shared/modal_exercise', { f: f } %>
								</div>
								<div class="col-12 text-center pt-3">
									<%= f.submit "記録", class:"btn btn-info px-5" %>
								</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/customs/management.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-10 pt-5">
			<div class="col-4 custom-index-title">
				<h2><i class="fas fa-file-alt"></i>タスク一覧</h2>
			</div>
			<div class="management-table">
				<table class="table">
					<tbody>
						<% @customs.each do |custom| %>
						<tr>
							<td><%= custom.task %></td>
							<td><%= link_to "削除", custom_path(custom), method: :delete, class:"btn btn-danger btn-sm" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-md-10 pt-2">
			<%= form_with model: @custom, local: true do |f| %>
				<h3><i class="fas fa-plus-square"></i><%= f.label :task ,"新しい習慣を作る"%></h3>
				<%= render 'shared/error_messages', {model: f.object} %>
				<div class="form-group form-inline">
					<%= f.text_field :task, class:"form-control w-75" %>
					<%= f.submit "作成", class:"btn btn-success" %>
			</div>
			<% end %>
		</div>
	</div>
</div>