config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/test_sign_in' => 'users/sessions#test_sign_in'
  end
  resource :users, only: [:show]
  get 'mypage/diary' => 'users#mypage_diary', as: 'mypage_diary'
  get 'mypage/post' => 'users#mypage_post', as: 'mypage_post'
  get 'mypage/like' => 'users#mypage_like', as: 'mypage_like'
  get 'chart/study' => 'users#chart_study', as: 'chart_study'
  get 'chart/sleeping' => 'users#chart_sleeping', as: 'chart_sleeping'
  get 'chart/exercise' => 'users#chart_exercise', as: 'chart_exercise'
  get 'customs/management' => 'customs#management'
  resources :customs, only: [:index, :create, :destroy]
  post 'task_complete/:id' => 'custom_records#create', as: 'task_complete'
  resources :posts, only: [:new, :index, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  get 'search/post' => 'posts#post_search', as: 'post_search'
  resources :genres, only: [:index, :create, :destroy]
  resources :diaries
  resources :lives, only: [:update]
  resources :life_recodes, only: [:index, :edit, :update]
  resources :inquiries, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/custom.rb
class Custom < ApplicationRecord
	belongs_to :user
	has_many :custom_records, dependent: :destroy

	validates :user_id, presence: true
	validates :task, presence: true, length:{maximum:20}
	validates :task_status, presence: true

	enum	task_status: [:未達成, :達成]

	def self.task_complete
		unless self.count == 0
			@task = self.pluck(:task_status)
			@task.all?{|task| task == "達成"}
		end
	end
end

app/models/custom_record.rb
class CustomRecord < ApplicationRecord
	belongs_to :custom
	belongs_to :user

	validates :user_id, presence: true
	validates :custom_id, presence: true
	validates :start_time, presence: true

end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :user
	belongs_to :genre

	validates :user_id, presence: true
	validates :genre_id, presence: true
	validates :title, presence: true, length:{maximum:50}
	validates :body, presence: true, length:{maximum:500}
	validates :diary_date, presence: true
	validates :adequacy, presence: true


end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :user
  has_many :diaries, dependent: :destroy

  validates :user_id, presence: true
  validates :name, presence: true, length:{maximum:15}
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/life.rb
class Life < ApplicationRecord
	belongs_to :user

	validates :user_id, presence: true
	validates :study_time, presence: true
	validates :sleeping_time, presence: true
	validates :exercise_time, presence: true
	validates :study_memo, length:{maximum:50}
	validates :sleeping_memo, length:{maximum:50}
	validates :exercise_memo, length:{maximum:50}
end

app/models/life_recode.rb
class LifeRecode < ApplicationRecord
	belongs_to :user

	validates :user_id, presence: true
	validates :study_time, presence: true
	validates :sleeping_time, presence: true
	validates :exercise_time, presence: true
	validates :study_memo, length:{maximum:100}
	validates :sleeping_memo, length:{maximum:100}
	validates :exercise_memo, length:{maximum:100}
	validates :life_date, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	#refileの設定
	attachment :post_image

	validates :user_id, presence: true
	validates :content, presence: true, length:{maximum:30}
	validates :post_image, presence: true

	def liked_by?(user)
  		likes.where(user_id: user.id).exists?
	end

	def save_tag(sent_tags)
		current_tags = self.tags.pluck(:name) unless self.tags.nil?
		old_tags = current_tags - sent_tags
		new_tags = sent_tags - current_tags

		old_tags.each do |old|
			self.tags.delete Tag.find_by(name: old)
		end

		new_tags.each do |new|
			new_post_tag = Tag.find_or_create_by(name: new)
			self.tags << new_post_tag
		end
	end

	def self.search(search)
		if search
			Post.where(['content LIKE ?', "%#{search}%"])
		else
			Post.all
		end
	end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, length:{maximum:15}


  #検索機能
  def self.search(search)
  	Tag.where(['name LIKE ?', "%#{search}%"])
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customs, dependent: :destroy
  has_many :custom_records, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :genres, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :life_recodes, dependent: :destroy
  #refileの設定
  attachment :profile_image

  validates :name, presence: true, length:{in: 2..10 }
  validates :acount_name, presence: true, format: { with: /@+\w{6,12}/}, uniqueness: true
  validates :introduction, presence: true, length:{maximum: 100}


  def self.test_sign_in
    User.find_by(email: "test_user@example.com")
  end

end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper


	def adequacy_status(diary)
		case diary.adequacy
			when 1
				image_tag asset_path('nicochan5.png'), class:"diary-image-mypage"
			when 2
				image_tag asset_path('nicochan4.png'), class:"diary-image-mypage"
			when 3
				image_tag asset_path('nicochan1.png'), class:"diary-image-mypage"
			when 4
				image_tag asset_path('nicochan2.png'), class:"diary-image-mypage"
			when 5
				image_tag asset_path('nicochan3.png'), class:"diary-image-mypage"
		end
	end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lives_helper.rb
module LivesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mylife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.png') %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrap">
      <%= render 'shared/header' %>
      <%= render 'shared/notifications' %>
        <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_chart_exercise.html.erb
<%= column_chart life_recodes.group(:life_date).sum(:exercise_time),discrete: true, xtitle: "日付（日）", ytitle: "時間（分）" %>

app/views/shared/_chart_sleeping.html.erb
<%= column_chart life_recodes.group(:life_date).sum(:sleeping_time), discrete: true, xtitle: "日付（日）", ytitle: "時間（分）" %>

app/views/shared/_chart_study.html.erb
<%= column_chart life_recodes.group(:life_date).sum(:study_time), discrete: true, xtitle: "日付（日）", ytitle: "時間（分）" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
	<div class="row error-box">
		<h4><%= model.errors.count %>件のエラーが発生しました</h4>
		<div class="col-10">
			<ul>
				<% model.errors.full_messages.each do |message| %>
					<li class=""><%= message %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-blue1">
	<div class="container">
		<div class="row align-items-center mt-2">
			<div class="offset-3 col-6 text-center">
				<span class="">©MyLife</span>
			</div>
			<div class="col-3 text-right">
				<span class="">
					<%= link_to "お問い合わせ", new_inquiry_path, class:"btn btn-bg" %>
				</span>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
<header class="sticky-top">
	<nav class="navbar navbar-expand-md navbar-dark bg-blue1">
		<div class="header-logo px-3">
			<%= link_to root_path, class:"navbar-brand", 'data-turbolinks':false do %>
				<%= image_tag 'mylife-logo5.png', size: '100x45' %>
			<% end %>
		</div>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navmenu" aria-controls="navmenu" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navmenu">
			<ul class="navbar-nav ml-auto">
				<% if user_signed_in? %>
					<li><%= link_to "ホーム", customs_path, class:"nav-item nav-link", 'data-turbolinks':false %></li>
					<li><%= link_to "マイページ", users_path, class:"nav-item nav-link", 'data-turbolinks':false %></li>
					<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-item nav-link" %></li>
				<% else %>
					<li><%= link_to "新規登録", new_user_registration_path, class:"nav-item nav-link", 'data-turbolinks':false %></li>
					<li><%= link_to "ログイン", user_session_path, class:"nav-item nav-link" %></li>
					<li><%= link_to "MyLifeとは", homes_about_path, class:"nav-item nav-link" %></li>
				<% end %>
			</ul>
		</div>
	</nav>
</header>

app/views/shared/_modal_exercise.html.erb
<buttom class="" data-toggle="modal" data-target="#execise">
	<i class="fas fa-clipboard ml-3"></i>
</buttom>

<div class="modal fade" id="execise" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<span>メモを書く</span>
				<div class="form-group">
					<%= f.text_field :exercise_memo, class:"form-control w-75" %>
					<%= f.submit "保存", class:"btn btn-success" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_modal_sleeping.html.erb
<buttom class="" data-toggle="modal" data-target="#sleeping">
	<i class="fas fa-clipboard ml-3"></i>
</buttom>

<div class="modal fade" id="sleeping" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<span>メモを書く</span>
				<div class="form-group">
					<%= f.text_field :sleeping_memo, class:"form-control w-75" %>
					<%= f.submit "保存", class:"btn btn-success" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_modal_study.html.erb
<buttom class="" data-toggle="modal" data-target="#study">
	<i class="fas fa-clipboard ml-3"></i>
</buttom>

<div class="modal fade" id="study" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<span>メモを書く</span>
				<div class="form-group">
					<%= f.text_field :study_memo, class:"form-control w-75" %>
					<%= f.submit "保存", class:"btn btn-success" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_mypage_diary.html.erb
<div class="row mt-3 overflow-auto mypage-box">
	<% diaries.each do |diary| %>
	<div class="offset-1 col-md-10 border my-2 py-4  bg-white">
		<div class="row">
			<div class="col-3">
				<div class="badge badge-dark py-2">
					<%= diary.diary_date.strftime("%Y年%m月%d日") %>
				</div>
				<div class="text-center pt-2">
					<%= adequacy_status(diary) %>
				</div>
			</div>
			<div class="col-9">
				<%= link_to diary_path(diary.id) do %>
					<h4 class="border-bottom"><%= diary.title %></h4>
				<% end %>
					<%= diary.body %>

			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/shared/_mypage_like.html.erb
<div class="row  overflow-auto mypage-box">
	<% @like_posts.each do |post| %>
	<div class="col-4">
		<%= attachment_image_tag(post, :post_image, :fill, 300, 300, format: "jpeg", fallback: "no-image-camera.png", class:"card-img-top") %>
	</div>
	<% end %>
</div>

app/views/shared/_mypage_post.html.erb
<div class="row overflow-auto mypage-box">
	<% @posts.each do |post| %>
	<div class="col-4">
		<%= attachment_image_tag(post, :post_image, :fill, 300, 300, format: "jpeg", fallback: "no-image-camera.png", class:"card-img-top") %>
	</div>
	<% end %>
</div>

app/views/shared/_notifications.html.erb
<div class="notifications text-center">
	<% flash.each do |key, value| %>
	<%= content_tag(:div, value, class: "alert alert-#{key}") %>
	<% end %>
</div>