config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/test_sign_in' => 'users/sessions#test_sign_in'
  end
  resource :users, only: [:show]
  get 'mypage/diary' => 'users#mypage_diary', as: 'mypage_diary'
  get 'mypage/post' => 'users#mypage_post', as: 'mypage_post'
  get 'mypage/like' => 'users#mypage_like', as: 'mypage_like'
  get 'chart/study' => 'users#chart_study', as: 'chart_study'
  get 'chart/sleeping' => 'users#chart_sleeping', as: 'chart_sleeping'
  get 'chart/exercise' => 'users#chart_exercise', as: 'chart_exercise'
  get 'customs/management' => 'customs#management'
  resources :customs, only: [:index, :create, :destroy]
  post 'task_complete/:id' => 'custom_records#create', as: 'task_complete'
  resources :posts, only: [:new, :index, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  get 'search/post' => 'posts#post_search', as: 'post_search'
  resources :genres, only: [:index, :create, :destroy]
  resources :diaries
  resources :lives, only: [:update]
  resources :life_recodes, only: [:index, :edit, :update]
  resources :inquiries, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/custom.rb
class Custom < ApplicationRecord
	belongs_to :user
	has_many :custom_records, dependent: :destroy

	validates :user_id, presence: true
	validates :task, presence: true, length:{maximum:20}
	validates :task_status, presence: true

	enum	task_status: [:未達成, :達成]

	def self.task_complete
		unless self.count == 0
			@task = self.pluck(:task_status)
			@task.all?{|task| task == "達成"}
		end
	end
end

app/models/custom_record.rb
class CustomRecord < ApplicationRecord
	belongs_to :custom
	belongs_to :user

	validates :user_id, presence: true
	validates :custom_id, presence: true
	validates :start_time, presence: true

end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :user
	belongs_to :genre

	validates :user_id, presence: true
	validates :genre_id, presence: true
	validates :title, presence: true, length:{maximum:50}
	validates :body, presence: true, length:{maximum:500}
	validates :diary_date, presence: true
	validates :adequacy, presence: true


end

app/models/genre.rb
class Genre < ApplicationRecord
  belongs_to :user
  has_many :diaries, dependent: :destroy

  validates :user_id, presence: true
  validates :name, presence: true, length:{maximum:15}
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/life.rb
class Life < ApplicationRecord
	belongs_to :user

	validates :user_id, presence: true
	validates :study_time, presence: true
	validates :sleeping_time, presence: true
	validates :exercise_time, presence: true
	validates :study_memo, length:{maximum:50}
	validates :sleeping_memo, length:{maximum:50}
	validates :exercise_memo, length:{maximum:50}
end

app/models/life_recode.rb
class LifeRecode < ApplicationRecord
	belongs_to :user

	validates :user_id, presence: true
	validates :study_time, presence: true
	validates :sleeping_time, presence: true
	validates :exercise_time, presence: true
	validates :study_memo, length:{maximum:100}
	validates :sleeping_memo, length:{maximum:100}
	validates :exercise_memo, length:{maximum:100}
	validates :life_date, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	#refileの設定
	attachment :post_image

	validates :user_id, presence: true
	validates :content, presence: true, length:{maximum:30}
	validates :post_image, presence: true

	def liked_by?(user)
  		likes.where(user_id: user.id).exists?
	end

	def save_tag(sent_tags)
		current_tags = self.tags.pluck(:name) unless self.tags.nil?
		old_tags = current_tags - sent_tags
		new_tags = sent_tags - current_tags

		old_tags.each do |old|
			self.tags.delete Tag.find_by(name: old)
		end

		new_tags.each do |new|
			new_post_tag = Tag.find_or_create_by(name: new)
			self.tags << new_post_tag
		end
	end

	def self.search(search)
		if search
			Post.where(['content LIKE ?', "%#{search}%"])
		else
			Post.all
		end
	end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, length:{maximum:15}


  #検索機能
  def self.search(search)
  	Tag.where(['name LIKE ?', "%#{search}%"])
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customs, dependent: :destroy
  has_many :custom_records, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :genres, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :life_recodes, dependent: :destroy
  #refileの設定
  attachment :profile_image

  validates :name, presence: true, length:{in: 2..10 }
  validates :acount_name, presence: true, format: { with: /@+\w{6,12}/}, uniqueness: true
  validates :introduction, presence: true, length:{maximum: 100}


  def self.test_sign_in
    User.find_by(email: "test_user@example.com")
  end

end

app/controllers/life_recodes_controller.rb
class LifeRecodesController < ApplicationController
	before_action :authenticate_user!

	def index
		@life_recodes = current_user.life_recodes.order(created_at: "DESC")
	end

	def edit
		@life_recode = LifeRecode.find(params[:id])
	end

	def update
		@life_recode = LifeRecode.find(params[:id])
		@life_recode.update(life_recode_params)
		redirect_to life_recodes_path
	end

	private

		def life_recode_params
			params.require(:life_recode).permit(:study_time, :sleeping_time, :exercise_time, :study_memo, :sleeping_memo, :exercise_memo)
		end
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper


	def adequacy_status(diary)
		case diary.adequacy
			when 1
				image_tag asset_path('nicochan5.png'), class:"diary-image-mypage"
			when 2
				image_tag asset_path('nicochan4.png'), class:"diary-image-mypage"
			when 3
				image_tag asset_path('nicochan1.png'), class:"diary-image-mypage"
			when 4
				image_tag asset_path('nicochan2.png'), class:"diary-image-mypage"
			when 5
				image_tag asset_path('nicochan3.png'), class:"diary-image-mypage"
		end
	end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/life_recodes_helper.rb
module LifeRecodesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/lives_helper.rb
module LivesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/life_recodes/edit.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-6 m-3">
			<div class="">
				<h3><%= @life_recode.life_date.strftime("%Y年%m月%d日") %>の記録</h3>
			</div>
			<%= form_with model:@life_recode do |f| %>
			<div class="form-group">
				<%= f.label :study_time %>
				<%= f.text_field :study_time, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :sleeping_time %>
				<%= f.text_field :sleeping_time, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :exercise_time %>
				<%= f.text_field :exercise_time, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :study_memo %>
				<%= f.text_field :study_memo, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :sleeping_memo %>
				<%= f.text_field :sleeping_memo, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :exercise_memo %>
				<%= f.text_field :exercise_memo, class:"form-control" %>
			</div>
				<%= f.submit "更新", class:"btn btn-primary" %>
			<% end %>

		</div>
	</div>
</div>

app/views/life_recodes/index.html.erb
<div class="container">
	<div class="page-title text-center b-primary mt-5">
		<h1>生活記録</h1>
	</div>
	<div class="row justify-content-center mt-5">
		<div class="col-md-9">
			<%= link_to "学習時間", chart_study_path, remote: true, class:"btn btn-primary" %>
			<%= link_to "睡眠時間", chart_sleeping_path, remote: true, class:"btn btn-info" %>
			<%= link_to "運動時間", chart_exercise_path, remote: true, class:"btn btn-success" %>
			<div id="chart">
				<%= render 'shared/chart_study', { life_recodes: @life_recodes } %>
			</div>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-md-10">
			<table class="table w-100">
				<thead>
					<tr>
						<th>日付</th>
						<th colspan="2">勉強時間(分)</th>
						<th colspan="2">睡眠時間(分)</th>
						<th colspan="2">運動時間(分)</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @life_recodes.each do |recode| %>
					<tr>
						<td><%= recode.life_date.strftime("%Y年%m月%d日") %></td>
						<td><%= recode.study_time %></td>
						<td>
							<% unless recode.study_memo.blank? %>
								<span class="" data-toggle="popover" data-placement="top" data-content="<%= recode.study_memo %>">
									<i class="fas fa-clipboard ml-3"></i>
								</span>
							<% end %>
						</td>
						<td><%= recode.sleeping_time %></td>
						<td>
							<% unless recode.sleeping_memo.blank? %>
							<span class="" data-toggle="popover" data-placement="top" data-content="<%= recode.sleeping_memo %>">
								<i class="fas fa-clipboard ml-3"></i>
							</span>
							<% end %>
						</td>
						<td><%= recode.exercise_time %></td>
						<td>
							<% unless recode.exercise_memo.blank? %>
							<span class="" data-toggle="popover" data-placement="top" data-content="<%= recode.exercise_memo %>">
								<i class="fas fa-clipboard ml-3"></i>
							</span>
							<% end %>
						</td>
						<td>
							<%= link_to "編集", edit_life_recode_path(recode.id), class:"btn btn-success" %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>